apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shinyproxy-operator

resources:
  - github.com/openanalytics/shinyproxy-operator/docs/deployment/bases/clustered?ref=v2.2.0
  - resources/shinyproxy-operator.namespace.yaml
