apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shinyproxy

resources:
  - github.com/openanalytics/shinyproxy-operator/docs/deployment/bases/redis-sentinel?ref=v2.2.1
  - github.com/openanalytics/shinyproxy-operator/docs/deployment/bases/namespaced?ref=v2.2.1
  - github.com/openanalytics/shinyproxy-operator/docs/deployment/bases/shinyproxy?ref=v2.2.1
  - resources/shinyproxy.namespace.yaml
  - resources/shinyproxy.shinyproxy.yaml

patches:
  - path: patches/redis.secret.yaml
