apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shinyproxy

resources:
  - github.com/openanalytics/shinyproxy-operator/docs/deployment/bases/shinyproxy?ref=v2.2.0
  - resources/redis.secret.yaml
  - resources/shinyproxy.shinyproxy.yaml
  - resources/shinyproxy.namespace.yaml
